# Generated by Django 4.1.2 on 2022-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="first",
            name="bachelors",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="certificate1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="certificate2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="certificate3",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="certificate4",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="dateofbirth",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="extraactivity1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="extraactivity2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="facebook",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="github",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="hobbies1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="hobbies2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="hobbies3",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="hobbies4",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="linkedin",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="location",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="projects1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="projects2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="projects3",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="projects4",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="skill1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="skill2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="skill3",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="skill4",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="twthpassedfrom",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="first",
            name="work",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
